### PR TITLE
Add T2 guide and warning

### PR DESCRIPTION
**Pull request by NoaHimesaka1873**
Yes, it's ready to be merged now!

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
@NoaHimesaka1873 you appear to have edited the docusarus config for your deployment, I will need to revert those changes for a clean merge with the master repo

**Review by Ast3risk-ops — CHANGES_REQUESTED** [review]
I'd like the docusarus config reverted to default (or what I have in my repo)

**Comment by NoaHimesaka1873** [comment]
Changed.

**Review by Ast3risk-ops — APPROVED** [review]
Yeah it all seems good, let's merge

**Pull request merged**
